name: "Nuget Pre-Release"

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack ./Source/Plex.Library/Plex.Library.csproj --configuration Release /p:Version=${VERSION} -p:PackageID=Plex.Api --output .
    - name: Push to Github Packages
      run: dotnet nuget push Plex.Api.${VERSION}.nupkg -s https://nuget.pkg.github.com/jensenkd/index.json -k ${GITHUB_TOKEN}
    - name: Push to Nuget.Org
      run: dotnet nuget push Plex.Api.${VERSION}.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }}
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
